FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
RUN mkdir /bomcupom
WORKDIR /bomcupom
COPY Gemfile /bomcupom/Gemfile
COPY Gemfile.lock /bomcupom/Gemfile.lock
RUN bundle install
COPY . /bomcupom